server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: docker
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect